#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env"

color(){ printf "\033[%sm%s\033[0m\n" "$1" "$2"; }
info(){ color "1;36" "$1"; }
ok(){ color "1;32" "$1"; }
warn(){ color "1;33" "$1"; }
err(){ color "1;31" "$1"; }

command_exists(){ command -v "$1" >/dev/null 2>&1; }

detect_os() {
  case "$(uname -s)" in
    Darwin) echo "macos" ;;
    Linux) echo "linux" ;;
    *) echo "unknown" ;;
  esac
}

write_env() {
  local ollama_url="$1"
  local ollama_base_url="$2"
  cat > "$ENV_FILE" <<EOF
# HyperSpace AGI v1.01 — generated by setup.sh
AUTHORITY_URL=http://authority:8080
OLLAMA_URL=${ollama_url}
OLLAMA_BASE_URL=${ollama_base_url}
OLLAMA_MODEL=phi3
WEBUI_SECRET_KEY=hyperspace-secret-change-me
EOF
}

print_next_steps() {
  echo
  info "Next steps"
  echo "1) Review .env — change OLLAMA_MODEL or WEBUI_SECRET_KEY if needed"
  echo "2) Start the stack:  docker compose up -d --build"
  echo "3) Open WebUI:       http://localhost:3000"
  echo "4) HyperSpace UI:    http://localhost:8085/dashboard"
  echo "5) Ollama API test:  curl http://localhost:11434/api/tags"
}

main() {
  OS_NAME="$(detect_os)"

  info "================================================"
  info " HyperSpace AGI v1.01 — setup"
  info "================================================"
  echo "Detected OS: ${OS_NAME}"
  echo

  if ! command_exists docker; then
    err "Docker is not installed or not in PATH."
    err "Install Docker Desktop: https://www.docker.com/products/docker-desktop"
    exit 1
  fi

  # ── macOS ───────────────────────────────────────────
  if [ "$OS_NAME" = "macos" ]; then
    warn "macOS detected."
    echo
    echo "  RECOMMENDED: install Ollama directly on the Mac host."
    echo "  Reason: Docker Desktop on macOS cannot expose 'localhost' to containers"
    echo "  the same way Linux does. Using Ollama on the host and pointing the"
    echo "  containers to 'host.docker.internal:11434' is simpler and more stable."
    echo
    echo "  Official download: https://ollama.com/download"
    echo "  Or via Homebrew:   brew install ollama"
    echo
    if command_exists ollama; then
      ok "  ✓ Ollama CLI found on this Mac — good to go!"
    else
      warn "  ✗ Ollama CLI not found. Install it, then re-run this script or"
      warn "    set OLLAMA_URL manually in .env."
    fi
    echo
    read -r -p "Configure HyperSpace to use host Ollama (host.docker.internal)? [Y/n] " ans
    ans="${ans:-Y}"
    if [[ "$ans" =~ ^[Yy]$ ]]; then
      write_env "http://host.docker.internal:11434" "http://host.docker.internal:11434"
      ok ".env written — macOS + Ollama on host"
    else
      write_env "http://ollama:11434" "http://ollama:11434"
      warn ".env written — macOS + Ollama in Docker (non-standard on Mac)"
    fi

  # ── Linux ───────────────────────────────────────────
  elif [ "$OS_NAME" = "linux" ]; then
    echo "Linux detected. Choose your Ollama mode:"
    echo
    echo "  1) Ollama in Docker   — OLLAMA_URL=http://ollama:11434"
    echo "     Best for a fully containerised stack."
    echo
    echo "  2) Ollama on host     — OLLAMA_URL=http://host.docker.internal:11434"
    echo "     Best if Ollama is already running as a systemd service."
    echo "     Note: requires 'extra_hosts: host.docker.internal:host-gateway'"
    echo "     in docker-compose.yml (already included)."
    echo
    if command_exists ollama; then
      ok "  ✓ Ollama CLI found on this Linux host."
    else
      warn "  ✗ Ollama CLI not found on host."
      echo "    To install: curl -fsSL https://ollama.com/install.sh | sh"
    fi
    echo
    read -r -p "Select mode [1/2, default 1]: " mode
    mode="${mode:-1}"
    if [ "$mode" = "2" ]; then
      write_env "http://host.docker.internal:11434" "http://host.docker.internal:11434"
      ok ".env written — Linux + Ollama on host"
    else
      write_env "http://ollama:11434" "http://ollama:11434"
      ok ".env written — Linux + Ollama in Docker"
    fi

  # ── fallback ─────────────────────────────────────────
  else
    warn "Unknown OS — using Docker-internal Ollama as default."
    write_env "http://ollama:11434" "http://ollama:11434"
    ok ".env written with fallback defaults"
  fi

  print_next_steps
}

main "$@"
